language: swift
jobs:
    include:
        - script: xcodebuild -project EasyLife.xcodeproj -scheme EasyLife -destination platform\=iOS\ Simulator,name=iPhone\ 8 test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
osx_image: xcode12
addons:
  homebrew:
    packages:
    - carthage
before_install:
  - chmod +x carthage.sh
  - ./carthage.sh bootstrap --platform ios --no-use-binaries
